### ISSUE TITLE
ENH: python-graphblas could use a logo!

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#171]
Any volunteers?  Please respect copywrite licenses.

**Comment by eriknw** [comment]
lmao, so I spent some time doodling.  These are pretty rough.  Enjoy!
![Project 3_1](https://user-images.githubusercontent.com/2058401/167239424-d65b9863-f2e5-4637-b15e-1139d3c1be49.png)
![Notes 3 20220506004541b](https://user-images.githubusercontent.com/2058401/167239460-6476f22f-6454-47ab-8853-a9813aeb1c20.png)
Thoughts and impressions?  Of these, I think maybe one or two have promise.  The rest were included for fun and brainstorming.

Also, I can't shake the feeling that I'm straight up copying some other logos from memory...

**Comment by ParticularMiner** [comment]
For my lack of innovation  😅:

![Python_GraphBLAS_logo](https://user-images.githubusercontent.com/78448465/167701906-f5a9313f-8c49-49b7-acb5-b9f383451e4f.svg)

**Comment by eriknw** [comment]
Heh, [Python logo] + [GraphBLAS logo] is a natural take for `python-graphblas`.

A different take: how about a mascot instead?  Everybody loves mascots, right? 😸

**Comment by eriknw** [comment]
I had some fun with [DALL-E mini (https://huggingface.co/spaces/dalle-mini/dalle-mini)](https://huggingface.co/spaces/dalle-mini/dalle-mini) and generated these:
![graph_logos2](https://user-images.githubusercontent.com/2058401/172948743-36f37a87-44d4-4759-8a9b-ad02b35b29c0.PNG)

Lots of interesting, fun things here.  If I had to call out one of them, I think 47 is pretty neat.  So is the style of 83 where the middle node is a cube.

Larger versions of these are available upon request.

**Comment by jim22k** [comment]
How about something like this?

![python-graphblas-sketch](https://user-images.githubusercontent.com/2807270/179295665-ca160f2a-5d4e-4f46-85e1-fd7e65b5b439.jpg)

We could even drop the `python-` part given that we have a snake as part of the word `graphblas` and the library is imported as `graphblas`.

We obviously need a real artist to make this look good, but it gives the general idea.

**Comment by jim22k** [comment]
![logo-light](https://user-images.githubusercontent.com/2807270/182746393-1b9e92c6-eaca-4827-9b10-76680a8bca47.svg)
![logo-dark](https://user-images.githubusercontent.com/2807270/182746409-c66bc550-9c3b-406a-8c48-ee078a71073c.svg)

Just made these up in Inkscape. Let me know what you think.

**Comment by SultanOrazbayev** [comment]
I liked in the doodles the variations that combine matrix brackets and graphs/networks, since it reflects matrix-operations on graphs.

**Comment by eriknw** [comment]
Sketch of latest proposal:

![IMG_20230913_115600700-small](https://github.com/python-graphblas/python-graphblas/assets/2058401/2b3ca4c9-23db-4ec0-aaa8-0695ca1a9dd1)
