### ISSUE TITLE
Use scipy sparse array, not matrix

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#181]
`grblas` tests raise this warning from `scipy.sparse`:
```
grblas/tests/test_io.py::test_matrix_to_from_networkx
  /home/erik/git/grblas/grblas/io.py:38: DeprecationWarning:

  The scipy.sparse array containers will be used instead of matrices
  in Networkx 3.0. Use `to_scipy_sparse_array` instead.
    ss = nx.convert_matrix.to_scipy_sparse_matrix(g)
```

**Comment by MridulS** [comment]
This was fixed in https://github.com/metagraph-dev/grblas/pull/195 but there is also needs to be a conversation about the `to_scipy_sparse_matrix` functions implemented in `io`. Should this be changed to `_array`? SciPy will be moving to the array interface in the future.

**Comment by eriknw** [comment]
Yeah, #195 was very narrow and only updated `io.from_networkx`.

We should probably deprecate `[to/from]_scipy_sparse_matrix` and add new functions `[to/from]_scipy_sparse_array` or `[to/from]_scipy_sparse`.

We can also make the conversions faster when using SuiteSparse:GraphBLAS like I did in `from_networkx`: https://github.com/metagraph-dev/grblas/issues/176.

When we do this, we should also update any notebook we have.  I think we should make our notebook CI check raise on deprecation warnings.
