### ISSUE TITLE
`Scalar.from_value()` segfaults when `value` type is unexpected

### ISSUE THREAD

**Issue by ParticularMiner** [python-graphblas/python-graphblas#184]
I hit a segfault while running `test_apply_binary()` in `test_matrix.py`.

The bug may be reproduced as follows.

```python
import grblas
from grblas import binary
from grblas import Matrix


data = [
    [3, 0, 3, 5, 6, 0, 6, 1, 6, 2, 4, 1],
    [0, 1, 2, 2, 2, 3, 3, 4, 4, 5, 5, 6],
    [3, 2, 3, 1, 5, 3, 7, 8, 3, 1, 7, 4],
]
A = Matrix.from_values(*data)
A.apply(binary.plus, left=A)
```
A `TypeError` exception was supposed to have been raised.  Instead, it segfaults. 

The bug appears to originate from the following call:
```python
from grblas import Scalar


Scalar.from_value(A)
```

FYI, older `grblas` versions did not segfault on these calls.

**Comment by eriknw** [comment]
Well, that's worrying.  Thanks for the report.

I'm unable to reproduce this.  What OS are you using @ParticularMiner?

**Comment by ParticularMiner** [comment]
Using Windows 10.

**Comment by eriknw** [comment]
These lines should exercise this, right?
https://github.com/metagraph-dev/grblas/blob/7dd54fd2f38d80a6cffa8a171182e1de929be54c/grblas/tests/test_matrix.py#L1065-L1068

**Comment by ParticularMiner** [comment]
Yeah.  But they segfault all the same, even after updating SuiteSparse:GraphBLAS to the latest version (6.2.5).

**Comment by eriknw** [comment]
I'm able to run tests on Windows in CI without segfaulting: https://github.com/metagraph-dev/grblas/pull/185 (still working to make everything pass).

Note that I didn't add any tests and am relying on the tests I referred to above.

This did point out that we probably need to test on Windows again.  My bad for ever dropping it.

**Comment by eriknw** [comment]
@ParticularMiner can you try to see if you still see this error in the latest `python-graphblas`?  We don't have conda-forge packages for it yet.  Also, you should update to the latest `python-suitesparse-graphblas`.

**Comment by ParticularMiner** [comment]
@eriknw @jim22k 

I've rechecked and found that this issue has been fixed in `python-graphblas`.  Exceptions are raised as expected and no more segfaults are being raised.  Thanks and well done!!  🎉

**Comment by ParticularMiner** [comment]
No problem @eriknw !  I'm curious about what you did to solve this.

**Comment by eriknw** [comment]
Heh, since you asked, this changed apparently fixed this (and other) segfaults: https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/41/files#diff-69e9d6c4a0d965b75605d9f281ebe5abb34e685738e5a712f34b9d47a25beaf1R47-R49

No idea why.

**Comment by ParticularMiner** [comment]
Did you inquire with `cffi` developers?  They might be able to help.

**Comment by eriknw** [comment]
Not yet, but we should.  Good suggestions.
