### ISSUE TITLE
Add contributing documentation

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#198]
We should make life easier for people who want to contribute.  We should add CONTRIBUTING.md to the repo.  Ideally, this should point to a section of our online documentation

**Comment by jim22k** [comment]
https://python-graphblas.readthedocs.io/en/latest/contributor_guide/index.html
^^^ Still needs work 😁 

Someone should get this updated before PyData Global and the nx+graphblas talk. We will hopefully have a lot more interested folks showing up here shortly and maybe a few will want to contribute.

**Comment by eriknw** [comment]
I like this! https://github.com/holoviz/panel/pull/4262

**Comment by eriknw** [comment]
Completed by #345 :rocket:
