### ISSUE TITLE
Computation between scalars

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#199]
I find it super-annoying that we're unable to use our operators to operate on scalars.  Should we support `ewise_add`, `ewise_mult`, `ewise_union`, and `apply` on scalars?  Also, support normal infix rules, such as `s + 1`.  But, should these return expressions?  Do we even dare to consider masking?

We _can_ do this.  We can use `s._as_vector()` to efficiently do this on GrB Scalars in SuiteSparse:GraphBLAS (other scalars would incur a copy into a new size 1 Vector).

**Comment by eriknw** [comment]
I think a big selling point for doing this is to allow users to more easily see what operators do.  For example, `unary.exp(1)` or `binary.plus(1, 2)`.

**Comment by jim22k** [comment]
Yes, let's do this.

**Comment by eriknw** [comment]
Given scalars `s` and `t`, I think we can support multiple syntaxes:
- `binary.plus(s | t)`
- `binary.plus(s | t, left_default=10, right_default=10)`
- `binary.plus(s & t)`
- `binary.plus(s, t)  # same as binary.plus(s & t)`
  - This is important to support for operating on Python scalars
- and as methods e.g. `s.ewise_mult(t, "+")`

I don't think masks make sense (for now). We may be able to support `s.select` where the first index is always `0` (mathematically, it's probably more correct to have no indices at all).
