### ISSUE TITLE
Making aggregators callable

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#238]
We punted on the option of making aggregators callable.  Let's revisit.

I think this is natural: `agg.max(A)` -> `Scalar`.  So, I think aggregators should be callable to reduce to scalar.

I think common practice should be/will be to reference aggregators as `agg.sum(v)`--i.e., from `agg` namespace.  This gives adequate context to keep it readable.

I think the big question is whether we should have a way to reduce rowwise or columnwise, such as:
- `agg.max(A, rowwise=True)`
- `agg.max.rowwise(A)`

I think keyword arguments are more discoverable, and other spellings exist.

**Comment by jim22k** [comment]
Yes, let's include this. The decisions made with `select` feel perfect here -- especially the `agg` namespace to help make the code readable and avoid confusion of whether this is an apply or a reduction.

I'm torn on how to specify rowwise/columnwise. I definitely prefer keywords, but in this case we actually have a ternary:
- None
- rowwise
- columnwise

The ideal would be an enum, but that feels like overkill. `agg.max.rowwise(A)` is intriguing, but not intuitive. Callable functions with callable attributes are possible in Python, but definitely not something I see often.

So I guess my vote would be `rowwise` and `columnwise` keyword-only arguments with a check that they can't both be set to True.
