### ISSUE TITLE
[Enhancement] Update Expression html repr

### ISSUE THREAD

**Issue by jim22k** [python-graphblas/python-graphblas#249]
The VectorExpression and MatrixExpression repr is functional, but leaves something to be desired. I usually want to see the result and usually don't care about the inputs. I propose that we:
1. Show the result without requiring the user to click the down arrow
2. Keep the expression in the top grey box -- that is helpful to see how the syntax translated into methods
3. Move the `Do expr.new() or other << expr to calculate the expression.` into a popout detail that sits next to the `gb.MatrixExpression:` on the very top row. We could even expand the detail to discuss expressions vs realized objects, what assumptions exist that allow you to work with expressions in subsequent expressions, etc. But don't show all of that by default. It needs to be hidden until the user mouses over or clicks or something.

**Comment by eriknw** [comment]
Yeah, the reprs haven't changed much the last couple years, and our syntax and normal usage patterns have changed significantly.  These suggested improvements sound great.

Are the reprs when using Python in the terminal to your liking?  This is what I normally use.
