### ISSUE TITLE
Deprecate `to_values` and `from_values` and use `to_coo` and `from_coo`

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#293]
For example, `to_coo` better matches the names of `to_csr` and `to_csc`, which were just added.

**Comment by eriknw** [comment]
@jim22k and I discussed this today, and we think we should _very gently_ deprecate `to_values` and `from_values`.

Step 1 is to remove usage and reference of `to_values` in code and documentation and use `to_coo` instead, and mention `to_values` will be become deprecated in its docstring. Also, mention the pending deprecation in release notes.

Step 2 is to give a deprecation warning. Maybe do this in a few months

Step 3 is to remove it. Maybe in a year.

@jim22k, should we rename `Vector.from_values` and `v.to_values`?  `from_coo`?  `to_sparse`?

**Comment by jim22k** [comment]
Maybe we leave Vectors as `from_values`. I'm struggling to come up with something better. COO could work. I don't love Sparse, even though that is what the format is called internally in suitesparse.

**Comment by eriknw** [comment]
I'm in favor of deprecating `Vector.from_values` and using `Vector.from_coo` instead.

**Comment by eriknw** [comment]
Closed by https://github.com/python-graphblas/python-graphblas/pull/331
