### ISSUE TITLE
bug: binder link does not work

### ISSUE THREAD

**Issue by SultanOrazbayev** [python-graphblas/python-graphblas#317]
When clicking on the binder link via `README.md `, I get the following error:

`Error loading python-graphblas/python-graphblas/HEAD!`

The logs should be accessible here:

https://mybinder.org/ca63e0d0-a6d2-43aa-9855-50401b677dd2

Copied below for persistence:

<details>

Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker4u2xk73c'...
HEAD is now at 5f30666 Improve `.ss.head` by using GxB iterators (#314)
Building conda environment for python=3.8
Using CondaBuildPack builder
Building conda environment for python=3.8
Building conda environment for python=3.8
Step 1/51 : FROM buildpack-deps:bionic
 ---> 06f90ff28102
Step 2/51 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 821bc573eafe
Step 3/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 74a8ed7b11d0
Step 4/51 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> a86019485f12
Step 5/51 : ENV LC_ALL en_US.UTF-8
 ---> Using cache
 ---> a1d07975e6c7
Step 6/51 : ENV LANG en_US.UTF-8
 ---> Using cache
 ---> 3c9a016a9d77
Step 7/51 : ENV LANGUAGE en_US.UTF-8
 ---> Using cache
 ---> 5e896526a8f7
Step 8/51 : ENV SHELL /bin/bash
 ---> Using cache
 ---> f2d400e8e4d8
Step 9/51 : ARG NB_USER
 ---> Using cache
 ---> 171bc9c8e5b7
Step 10/51 : ARG NB_UID
 ---> Using cache
 ---> 6753e3911fe5
Step 11/51 : ENV USER ${NB_USER}
 ---> Using cache
 ---> 457e01fc449f
Step 12/51 : ENV HOME /home/${NB_USER}
 ---> Using cache
 ---> 8543380f4268
Step 13/51 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> c0285ec5ae23
Step 14/51 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> cf07a06db515
Step 15/51 : EXPOSE 8888
 ---> Using cache
 ---> d1a9029e9ad8
Step 16/51 : ENV APP_BASE /srv
 ---> Using cache
 ---> d9e43911d221
Step 17/51 : ENV CONDA_DIR ${APP_BASE}/conda
 ---> Using cache
 ---> 931d90fb99df
Step 18/51 : ENV NB_PYTHON_PREFIX ${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> 9544828c0f02
Step 19/51 : ENV NPM_DIR ${APP_BASE}/npm
 ---> Using cache
 ---> 4eb35452f894
Step 20/51 : ENV NPM_CONFIG_GLOBALCONFIG ${NPM_DIR}/npmrc
 ---> Using cache
 ---> 0056a543e89c
Step 21/51 : ENV NB_ENVIRONMENT_FILE /tmp/env/environment.lock
 ---> Using cache
 ---> 07dd8839612c
Step 22/51 : ENV MAMBA_ROOT_PREFIX ${CONDA_DIR}
 ---> Using cache
 ---> f1388d2b77b3
Step 23/51 : ENV MAMBA_EXE ${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> 3472bba35081
Step 24/51 : ENV KERNEL_PYTHON_PREFIX ${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> db41eb8a9605
Step 25/51 : ENV PATH ${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> d34bcc1144e8
Step 26/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e9-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-e9bee0 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> 9cf4b8dec3eb
Step 27/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e9-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e8-2elock-e2192b /tmp/env/environment.lock
 ---> Using cache
 ---> 88caaea34ba7
Step 28/51 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e9-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-41d468 /tmp/install-base-env.bash
 ---> Using cache
 ---> f3e1686eda7b
Step 29/51 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Running in 608802478b29
[91m++ dirname /tmp/install-base-env.bash
[0m[91m+ cd /tmp
[0m[91m+ export MAMBA_VERSION=0.25.0
+ MAMBA_VERSION=0.25.0
[0m[91m+ export CONDA_VERSION=4.13.0
+ CONDA_VERSION=4.13.0
+ URL=https://anaconda.org/conda-forge/micromamba/0.25.0/download/linux-64/micromamba-0.25.0-0.tar.bz2
[0m[91m+ unset HOME
[0m[91m+ mkdir -p /srv/conda
[0m[91m+ export MICROMAMBA_EXE=/usr/local/bin/micromamba
+ MICROMAMBA_EXE=/usr/local/bin/micromamba
[0m[91m+ wget -qO- https://anaconda.org/conda-forge/micromamba/0.25.0/download/linux-64/micromamba-0.25.0-0.tar.bz2
[0m[91m+ tar -xvj bin/micromamba
[0mbin/micromamba
[91mtime: 2.669
[0m[91m+ mv bin/micromamba /usr/local/bin/micromamba
[0m[91m+ chmod 0755 /usr/local/bin/micromamba
[0m[91m++ /usr/local/bin/micromamba shell hook -p /srv/conda -s posix
[0m[91m+ eval '
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause

__add_sys_prefix_to_path() {
    # In dev-mode MAMBA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -z "${MAMBA_ROOT_PREFIX}" ]; then
        return 0
    fi;

    if [ -n "${WINDIR+x}" ]; then
        PATH="${MAMBA_ROOT_PREFIX}/bin:${PATH}"
        PATH="${MAMBA_ROOT_PREFIX}/Scripts:${PATH}"
        PATH="${MAMBA_ROOT_PREFIX}/Library/bin:${PATH}"
        PATH="${MAMBA_ROOT_PREFIX}/Library/usr/bin:${PATH}"
        PATH="${MAMBA_ROOT_PREFIX}/Library/mingw-w64/bin:${PATH}"
        PATH="${MAMBA_ROOT_PREFIX}:${PATH}"
    else
        PATH="${MAMBA_ROOT_PREFIX}/bin:${PATH}"
    fi
    \export PATH
}

__conda_hashr() {
    if [ -n "${ZSH_VERSION:+x}" ]; then
        \rehash
    elif [ -n "${POSH_VERSION:+x}" ]; then
        :  # pass
    else
        \hash -r
    fi
}

__mamba_activate() {
    \local cmd="$1"
    shift
    \local ask_conda
    CONDA_INTERNAL_OLDPATH="${PATH}"
    __add_sys_prefix_to_path
    ask_conda="$(PS1="$PS1" "/usr/local/bin/micromamba" shell --shell bash "$cmd" "$@")" || \return $?
    rc=$?
    PATH="${CONDA_INTERNAL_OLDPATH}"
    \eval "$ask_conda"
    if [ $rc != 0 ]; then
        \export PATH
    fi
    __conda_hashr
}

__mamba_reactivate() {
    \local ask_conda
    CONDA_INTERNAL_OLDPATH="${PATH}"
    __add_sys_prefix_to_path
    ask_conda="$(PS1="$PS1" "/usr/local/bin/micromamba" shell --shell bash reactivate)" || \return $?
    PATH="${CONDA_INTERNAL_OLDPATH}"
    \eval "$ask_conda"
    __conda_hashr
}

micromamba() {
    if [ "$#" -lt 1 ]; then
        "/usr/local/bin/micromamba"
    else
        \local cmd="$1"
        shift
        case "$cmd" in
            activate|deactivate)
                __mamba_activate "$cmd" "$@"
                ;;
            install|update|upgrade|remove|uninstall)
                CONDA_INTERNAL_OLDPATH="${PATH}"
                __add_sys_prefix_to_path
                "/usr/local/bin/micromamba" "$cmd" "$@"
                \local t1=$?
                PATH="${CONDA_INTERNAL_OLDPATH}"
                if [ $t1 = 0 ]; then
                    __mamba_reactivate
                else
                    return $t1
                fi
                ;;
            *)
                CONDA_INTERNAL_OLDPATH="${PATH}"
                __add_sys_prefix_to_path
                "/usr/local/bin/micromamba" "$cmd" "$@"
                \local t1=$?
                PATH="${CONDA_INTERNAL_OLDPATH}"
                return $t1
                ;;
        esac
    fi
}

if [ -z "${CONDA_SHLVL+x}" ]; then
    \export CONDA_SHLVL=0
    # In dev-mode MAMBA_EXE is python.exe and on Windows
    # it is in a different relative location to condabin.
    if [ -n "${_CE_CONDA+x}" ] && [ -n "${WINDIR+x}" ]; then
        PATH="${MAMBA_ROOT_PREFIX}/condabin:${PATH}"
    else
        PATH="${MAMBA_ROOT_PREFIX}/condabin:${PATH}"
    fi
    \export PATH

    # We'\''re not allowing PS1 to be unbound. It must at least be set.
    # However, we'\''re not exporting it, which can cause problems when starting a second shell
    # via a first shell (i.e. starting zsh from bash).
    if [ -z "${PS1+x}" ]; then
        PS1=
    fi
fi

if [ -n "${ZSH_VERSION:+x}" ]; then
  autoload -U +X compinit && compinit
  autoload -U +X bashcompinit && bashcompinit

  _umamba_zsh_completions()
  {
    COMPREPLY=($($MAMBA_EXE completer "${(@s: :)${(@s: :)COMP_LINE}:1}"))
  }

  complete -o default -F _umamba_zsh_completions micromamba
fi
if [ -n "${BASH_VERSION:+x}" ]; then
  _umamba_bash_completions()
  {
    COMPREPLY=($($MAMBA_EXE completer "${COMP_WORDS[@]:1}"))
  }
  complete -o default -F _umamba_bash_completions micromamba
fi'
[0m[91m++ '[' -z '' ']'
++ export CONDA_SHLVL=0
++ CONDA_SHLVL=0
[0m[91m++ '[' -n '' ']'
++ PATH=/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export PATH
++ '[' -z '' ']'
++ PS1=
++ '[' -n '' ']'
++ '[' -n x ']'
++ complete -o default -F _umamba_bash_completions micromamba
+ micromamba activate
+ '[' 1 -lt 1 ']'
+ local cmd=activate
+ shift
+ case "$cmd" in
+ __mamba_activate activate
+ local cmd=activate
+ shift
+ local ask_conda
+ CONDA_INTERNAL_OLDPATH=/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ __add_sys_prefix_to_path
+ '[' -z /srv/conda ']'
+ '[' -n '' ']'
+ PATH=/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export PATH
[0m[91m++ PS1=
++ /usr/local/bin/micromamba shell --shell bash activate
[0m[91m+ ask_conda='PS1='\''(base) '\''
export PATH='\''/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\''
export CONDA_PREFIX='\''/srv/conda'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''base'\''
export CONDA_PROMPT_MODIFIER='\''(base) '\'''
+ rc=0
+ PATH=/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[0m[91m+ eval 'PS1='\''(base) '\''
export PATH='\''/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'\''
export CONDA_PREFIX='\''/srv/conda'\''
export CONDA_SHLVL='\''1'\''
export CONDA_DEFAULT_ENV='\''base'\''
export CONDA_PROMPT_MODIFIER='\''(base) '\'''
[0m[91m++ PS1='(base) '
[0m[91m++ export PATH=/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export CONDA_PREFIX=/srv/conda
++ CONDA_PREFIX=/srv/conda
[0m[91m++ export CONDA_SHLVL=1
++ CONDA_SHLVL=1
[0m[91m++ export CONDA_DEFAULT_ENV=base
++ CONDA_DEFAULT_ENV=base
++ export 'CONDA_PROMPT_MODIFIER=(base) '
++ CONDA_PROMPT_MODIFIER='(base) '
[0m[91m+ '[' 0 '!=' 0 ']'
+ __conda_hashr
[0m[91m+ '[' -n '' ']'
+ '[' -n '' ']'
+ hash -r
[0m[91m+ export PATH=/tmp/bin:/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/tmp/bin:/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ cat
[0m[91m+ micromamba install conda=4.13.0 mamba=0.25.0 -y
+ '[' 4 -lt 1 ']'
[0m[91m+ local cmd=install
[0m[91m+ shift
+ case "$cmd" in
[0m[91m+ CONDA_INTERNAL_OLDPATH=/tmp/bin:/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ __add_sys_prefix_to_path
[0m[91m+ '[' -z /srv/conda ']'
+ '[' -n '' ']'
[0m[91m+ PATH=/srv/conda/bin:/tmp/bin:/srv/conda/bin:/srv/conda/condabin:/srv/conda/envs/notebook/bin:/srv/conda/bin:/srv/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ export PATH
[0m[91m+ /usr/local/bin/micromamba install conda=4.13.0 mamba=0.25.0 -y
[0m
                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

Transaction

  Prefix: /srv/conda

  Updating specs:

   - conda=4.13.0
   - mamba=0.25.0

  Package                        Version  Build               Channel                   Size
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  Install:
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  + _libgcc_mutex                    0.1  conda_forge         conda-forge/linux-64       3kB
  + _openmp_mutex                    4.5  2_gnu               conda-forge/linux-64      24kB
  + brotlipy                       0.7.0  py310h5764c6d_1005  conda-forge/linux-64     351kB
  + bzip2                          1.0.8  h7f98852_4          conda-forge/linux-64     496kB
  + c-ares                        1.18.1  h7f98852_0          conda-forge/linux-64     115kB
  + ca-certificates            2022.9.24  ha878542_0          conda-forge/linux-64     154kB
  + certifi                    2022.9.24  pyhd8ed1ab_0        conda-forge/noarch       159kB
  + cffi                          1.15.1  py310h255011f_2     conda-forge/linux-64     237kB
  + charset-normalizer             2.1.1  pyhd8ed1ab_0        conda-forge/noarch        36kB
  + colorama                       0.4.6  pyhd8ed1ab_0        conda-forge/noarch        25kB
  + conda                         4.13.0  py310hff52083_2     conda-forge/linux-64       1MB
  + conda-package-handling         1.9.0  py310h5764c6d_1     conda-forge/linux-64       1MB
  + cryptography                  38.0.3  py310h597c629_0     conda-forge/linux-64       2MB
  + icu                             70.1  h27087fc_0          conda-forge/linux-64      14MB
  + idna                             3.4  pyhd8ed1ab_0        conda-forge/noarch        57kB
  + keyutils                       1.6.1  h166bdaf_0          conda-forge/linux-64     118kB
  + krb5                          1.19.3  h3790be6_0          conda-forge/linux-64       2MB
  + ld_impl_linux-64                2.39  hc81fddc_0          conda-forge/linux-64     778kB
  + libarchive                     3.5.2  hb890918_3          conda-forge/linux-64       2MB
  + libcurl                       7.86.0  h7bff187_1          conda-forge/linux-64     357kB
  + libedit                 3.1.20191231  he28a2e2_2          conda-forge/linux-64     124kB
  + libev                           4.33  h516909a_1          conda-forge/linux-64     106kB
  + libffi                         3.4.2  h7f98852_5          conda-forge/linux-64      58kB
  + libgcc-ng                     12.2.0  h65d4601_19         conda-forge/linux-64     954kB
  + libgomp                       12.2.0  h65d4601_19         conda-forge/linux-64     466kB
  + libiconv                        1.17  h166bdaf_0          conda-forge/linux-64       1MB
  + libmamba                      0.25.0  hd8a31e3_2          conda-forge/linux-64       2MB
  + libmambapy                    0.25.0  py310hab0e683_2     conda-forge/linux-64     304kB
  + libnghttp2                    1.47.0  hdcd2b5c_1          conda-forge/linux-64     828kB
  + libnsl                         2.0.0  h7f98852_0          conda-forge/linux-64      31kB
  + libsolv                       0.7.22  h6239696_0          conda-forge/linux-64     454kB
  + libsqlite                     3.39.4  h753d276_0          conda-forge/linux-64     822kB
  + libssh2                       1.10.0  haa6b8db_3          conda-forge/linux-64     239kB
  + libstdcxx-ng                  12.2.0  h46fd767_19         conda-forge/linux-64       4MB
  + libuuid                       2.32.1  h7f98852_1000       conda-forge/linux-64      28kB
  + libxml2                       2.10.3  h7463322_0          conda-forge/linux-64     773kB
  + libzlib                       1.2.13  h166bdaf_4          conda-forge/linux-64      66kB
  + lz4-c                          1.9.3  h9c3ff4c_1          conda-forge/linux-64     184kB
  + lzo                             2.10  h516909a_1000       conda-forge/linux-64     321kB
  + mamba                         0.25.0  py310hf87f941_2     conda-forge/linux-64      47kB
  + ncurses                          6.3  h27087fc_1          conda-forge/linux-64       1MB
  + openssl                       1.1.1s  h166bdaf_0          conda-forge/linux-64       2MB
  + pip                           22.3.1  pyhd8ed1ab_0        conda-forge/noarch         2MB
  + pybind11-abi                       4  hd8ed1ab_3          conda-forge/noarch        10kB
  + pycosat                        0.6.4  py310h5764c6d_1     conda-forge/linux-64     111kB
  + pycparser                       2.21  pyhd8ed1ab_0        conda-forge/noarch       103kB
  + pyopenssl                     22.1.0  pyhd8ed1ab_0        conda-forge/noarch       125kB
  + pysocks                        1.7.1  pyha2e5f31_6        conda-forge/noarch        19kB
  + python                        3.10.6  h582c2e5_0_cpython  conda-forge/linux-64      30MB
  + python_abi                      3.10  2_cp310             conda-forge/linux-64       4kB
  + readline                       8.1.2  h0f457ee_0          conda-forge/linux-64     298kB
  + reproc                        14.2.3  h7f98852_0          conda-forge/linux-64      29kB
  + reproc-cpp                    14.2.3  h9c3ff4c_0          conda-forge/linux-64      20kB
  + requests                      2.28.1  pyhd8ed1ab_1        conda-forge/noarch        55kB
  + ruamel_yaml                  0.15.80  py310h5764c6d_1008  conda-forge/linux-64     259kB
  + setuptools                    65.5.1  pyhd8ed1ab_0        conda-forge/noarch       748kB
  + tk                            8.6.12  h27826a3_0          conda-forge/linux-64       3MB
  + toolz                         0.12.0  pyhd8ed1ab_0        conda-forge/noarch        49kB
  + tqdm                          4.64.1  pyhd8ed1ab_0        conda-forge/noarch        83kB
  + tzdata                         2022f  h191b570_0          conda-forge/noarch       121kB
  + urllib3                      1.26.11  pyhd8ed1ab_0        conda-forge/noarch       104kB
  + wheel                         0.38.2  pyhd8ed1ab_0        conda-forge/noarch        32kB
  + xz                             5.2.6  h166bdaf_0          conda-forge/linux-64     418kB
  + yaml                           0.2.5  h7f98852_2          conda-forge/linux-64      89kB
  + yaml-cpp                       0.7.0  h27087fc_2          conda-forge/linux-64     220kB
  + zstd                           1.5.2  h6239696_4          conda-forge/linux-64     459kB

  Summary:

  Install: 66 packages

  Total download: 79MB

â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

Transaction starting
Linking _libgcc_mutex-0.1-conda_forge
Failed to connect to event stream

</details>

This is not a blocker or a pressing issue, just wanted to document it.

**Comment by eriknw** [comment]
Fixed it--thanks so much @SultanOrazbayev! This has been broken since we renamed some things in April. Although it's not a blocker, I consider it a pressing issue.
