### ISSUE TITLE
Deprecate `dup` and use `copy` and `astype` instead?

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#335]
Most libraries follow numpy's lead and have e.g. `a.copy()` and `a.astype(type)`.  We use `dup` in `python-graphblas` to better match the C spec, and we added the ability to change the type.

I think we should consider deprecating `dup` and split the functionality into `copy` and `astype`. Thoughts?

We'll need to decide what to do about `clear=` keyword added in https://github.com/python-graphblas/python-graphblas/pull/275, which gives `np.empty_like` behavior and I think is pretty useful.

**Comment by eriknw** [comment]
Upon closer consideration, I'm fine having `dup` the way it is. It's not hard to find, and it follows many of our idioms used elsewhere (such as in `new`) such as changing dtype and passing a mask. We do some things differently than numpy and pandas, and that's okay.

@jim22k do you want more time to consider this or can we close this issue?

**Comment by jim22k** [comment]
We can close it. I agree that we are different enough from numpy to deviate. After all, we never use `out=` in functions.
