### ISSUE TITLE
Achieve 100% code coverage

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#355]
Let's aspire to reach 100% code coverage when running the test suite.  If we can hit this, then let's (probably) enforce it.

Coverage reports are here:
- https://coveralls.io/github/python-graphblas/python-graphblas
- https://app.codecov.io/gh/python-graphblas/python-graphblas

At times, it is appropriate to add `# pragma: no cover` or `# pragma: no branch` on uncovered code.  When this is done, we should try to provide a short annotation or description for why it's not covered. For example, we use `# pragma: no cover (numba)` for functions jitted with numba. Here is a list of annotations we currently use:
- `numba`: function is jitted with numba
- `sanity`: this code should _never_ be possible to be reached, but if it is, we want a hard failure
- `safety`: reasonably paranoid code that is difficult to test, but is desirable for defensive, maintainable code
- `suitesparse`: more specific than `safety`, this code may be reached by an error originating from SuiteSparse:GraphBLAS that is difficult for us to trigger
- `deprecated`: the code is deprecated and we don't care about its coverage
- `debug`: code helpful for debugging and is not covered in normal usage; often in tests
- `import`: code branch depends on the (un)availability of an optional package
- `ipython`: code that is exercised when used in IPython or Jupyter and is hard for us to test
- `unused`: code that could be safely removed (and maybe we should), but we're keeping it for possible future use
- `???`: the code _ought_ to be reported as covered, but `coverage` may not be working properly

We should aspire to not have bare `# pragma: no cover`. Let's try to always have a reason.

I marked this as "good first issue", b/c some coverage should be straightforward, and I would be _delighted_ to see tests added for the sole purpose of adding coverage.

I also marked this as "good second issue", b/c some coverage will probably be more difficult to achieve.

If anybody has questions for how to cover specific lines, feel free to respond here, ask us on Discord, or join our weekly community call.

We're currently above 99%, so we're not far off!

**Comment by eriknw** [comment]
I don't think we should enforce a coverage limit. This is not friendly to new contributors, and I think it's more valuable to have randomized tests as currently done, which comes at the cost of occasional coverage misses.

**Comment by jim22k** [comment]
Agree. High level of coverage is nice, and we should be aware of significant drops in coverage (and open future PRs to fix). But strict 100% requirement is not worth the cost in my opinion.
