### ISSUE TITLE
Creating Matrix from an edgelist?

### ISSUE THREAD

**Issue by SultanOrazbayev** [python-graphblas/python-graphblas#372]
Do you think it's useful to have a method for creating a matrix via an edge list? This is the rough API:

```python
from graphblas import Matrix


edge_list = [(0,1), (0,2), (0,3)]
A = Matrix.from_edge_list(edge_list, edge_value=2, nrows=4, ncols=4, name='test')
# these would be all the possible kwargs
# edge_value - default is 1
# nrows/ncols - default would be imputed from the list
```

To give context why this might be useful, I'm writing a small tutorial and it seems that having an edge-list based matrix creation might be more intuitive (to avoid introducing coo/csr/dcsr/etc notations, which are not IMO beginner-friendly).

**Comment by eriknw** [comment]
I love tutorial-driven development! +1 from me.

I agree this could be nice to have. NetworkX has `from_edgelist`:
https://networkx.org/documentation/stable/reference/generated/networkx.convert.from_edgelist.html

How about this API?
```python
def from_edgelist(edgelist, values=1.0, dtype=None, *, nrows=None, ncols=None, dup_op=None, name=None):
```
I like `1.0` as the default value so the default dtype is `FP64`, which is the most flexible dtype (and is also the default dtype for e.g. `A = Matrix()`).

I think it would be nice if `edgelist` could be 2-column `numpy.ndarray`, 2-column `pandas.DataFrame`, or a Python Sequence or Iterable of Sequences or Iterables.

For Python data (i.e., not numpy), this core (i.e, needs better error messages) could probably be:
```python
    ...
    rows, columns = zip(*edgelist)
    return Matrix.from_coo(rows, columns, values, dtype, **kwargs)
```
@SultanOrazbayev what do you think about `matrix.to_edgelist`? I think it could pretty much be:
```python
    rows, columns, values = self.to_values()
    return (np.columnstack([rows, columns]), values)
```
Relatedly, we could have `gb.io.from_pandas_edgelist` and `gb.io.to_pandas_edgelist` (again, see [`networkx`](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html), but this is different (and I believe separable) from the issue of adding `Matrix.from_edgelist`).

**Comment by SultanOrazbayev** [comment]
Interesting, didn't think about these other methods. Yes, this looks useful to have.

**Comment by eriknw** [comment]
@SultanOrazbayev, there's something else I find interesting about your proposal: having a default for the values.

Should e.g. `from_coo`, `from_csr`, `from_dcsc` also have a default values of `1.0`?

**Comment by SultanOrazbayev** [comment]
> Should e.g. from_coo, from_csr, from_dcsc also have a default values of 1.0?

Yes, I think this could be useful.

**Comment by jim22k** [comment]
I like the concept, and I think we should follow NetworkX's wisdom and keep DataFrames separate from simpler edgelists. NetworkX has both [`from_edgelist`](https://networkx.org/documentation/stable/reference/generated/networkx.convert.from_edgelist.html#from-edgelist) and [`from_pandas_edgelist`](https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html) to deal with the fact that the source, target, and value columns may not be in sequential order in DataFrames.

I am okay with a default value of 1.0 and default dtype of FP64.
