### ISSUE TITLE
Question on API for `from_edgelist` with respect to defining adjacency matrices.

### ISSUE THREAD

**Issue by SultanOrazbayev** [python-graphblas/python-graphblas#412]
When creating a simple example I got a somewhat unexpected result:

```python
from graphblas import Matrix

edge_list = [(0, 1), (0, 2), (0, 3)]
A = Matrix.from_edgelist(edge_list)
print(A.shape)
# (1, 4)
```

Looking through the code, I see that for generality it does make sense to not impose square shape on a matrix defined via `from_coo`:

https://github.com/python-graphblas/python-graphblas/blob/c3baea8d55df1ab015e27c9b9db16e40f64f446b/graphblas/core/matrix.py#L871-L879

However, for matrices created via `from_edgelist`, wouldn't it be safer to impose `nrows=ncols=max(n for edge in edge_list for n in edge)`? This would be added specifically inside `from_edgelist` to add the nrows/ncols to the call for `from_coo`. It's also fine to require the user to pass the nrows/ncols explicitly, but in that case it might be good to either add a warning message or update the docs to note this behaviour.

**Comment by SultanOrazbayev** [comment]
This will also be relevant when constructing incidence matrices, in which case the symmetry is not needed. It might be too early to discuss the API for that, but one option would be to add a kwarg asking for matrix type ('adjacency', 'incidence') and then adjust the downstream logic for each case.

**Comment by eriknw** [comment]
Hmm, I think I'd like to keep the current behaviro and not assume it's square, but I see where you're coming from. Feel free to add to any docs at any time 😃 

Would you have found, used, and liked a keyword argument to ensure it's square? For example, `Matrix.from_edgelist(edge_list, square=True)` (`is_square=`? `ensure_square=`?)

**Comment by eriknw** [comment]
> This will also be relevant when constructing incidence matrices, in which case the symmetry is not needed. It might be too early to discuss the API for that, but one option would be to add a kwarg asking for matrix type ('adjacency', 'incidence') and then adjust the downstream logic for each case.

Ah, so you're thinking to add the matrix type ("adjacency", "incidence") to `Matrix.from_` and `io.from_` methods? I'd be curious to see how that works out and feels in practice. `B = io.from_networkx(G, matrix="incidence")` seems okay, but I think a lot depends on the arguments we'll want to control the incidence matrix.

My current thinking is that I probably prefer `io.incidence_from_*` and `io.incidence_to*` functions, such as
- `io.incidence_from_networkx`
- `io.incidence_from_coo`
- `io.incidence_from_edgelist`
- `io.incidence_to_networkx`
- etc

but maybe some belong on `Matrix` directly such as `Matrix.incidence_from_coo`.

**Comment by SultanOrazbayev** [comment]
Based on the discussion during today's call, I think the best way forward is to document this behaviour and not make any changes to the current API.
