### ISSUE TITLE
Default size of objects

### ISSUE THREAD

**Issue by eriknw** [python-graphblas/python-graphblas#520]
@michelp raised a point that default size of `0` for matrix and vector dimensions isn't very useful most of the time. Let's discuss.

# `0` default
This is what we have today:
```python
>>> Matrix().shape
(0, 0)
>>> Vector().shape
(0,)
```
Why this is tolerable:
- Objects have `.resize(...)` methods to change their shape

Why this is good:
- It is consistent for all possible backends
- It makes it easy to create "dummy" objects when experimenting with syntax or showing things off
- It encourages (but doesn't requires) users to be explicit about the shape of their objects, which improves readability

Why this is bad:
- `0` is almost never useful in practice, because it has no data!

# `1` default
Why this is better than `0`:
- The object can have a value, which makes it much more "tangible" and useful when experimenting or showing off
  - e.g., it's friendly for beginners
- It makes it easy to create row vector and column vector matrices:
  - `rowvec = Matrix(ncols=42)`
  - `colvec = Matrix(nrows=42)`
 
Why this is worse than `0`:
- I don't know, is it ever worse than `0`?

# `GrB_MAX_INDEX + 1` as default
Why this better than `0`
- It is sometimes useful in practice

Why this is worse than `0`
- The value of `GrB_MAX_INDEX` is not specified by the C spec. It will likely be different for different backends.
- If you just want to create a "dummy" object for experimenting or showing off, I find having very large numbers for nrows and ncols in the repr to be jarring, and I don't think this is as user-friendly for people learning about GraphBLAS
- It may be a surprising default and explicit would be better than implicit
- When I have used very large hypersparse objects, I typically choose sizes that make sense for what I'm doing, which may be e.g. `2**32` or `2**48`

# No default
Why this is better:
- Require the user to always be explicit; there are no implicit assumptions

Why this is worse:
- More annoying to create objects for experimentation and showing off

# Final thoughts
You can probably tell that my preference is to choose what is best for beginners and what will help people with their learning curve.

If somebody is working on a problem that requires lots of row and column vectors or max-sized hypersparse objects, I think it's easy to create convenience functions such as `row_vector`, `col_vector`, `hypervector`, `hypermatrix`, etc.:

**Comment by SultanOrazbayev** [comment]
No default or 0 seem to be more explicit/least surprising to me. I would go for 0 as preference (or no default as second preference). 

Some examples:

```python
from pandas import DataFrame
DataFrame() # empty dataframe, no rows, no cols
```

```python
from numpy import array
array() # will trigger error (no default assumption)
```

**Comment by eriknw** [comment]
Thanks @SultanOrazbayev, comparing to other packages is often a good way to provide guidance and understand user expectation.

`xarray` (one of my favorites) also defaults to empty structures:
```python
>>> import xarray as xr
>>> xr.DataArray().shape
()
>>> xr.Dataset()
<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*
```
`pandas` and `xarray` are similar to GraphBLAS in that they both have two main non-scalar data structures, one of which is logically  comprised of the other. For pandas, DataFrame is logically comprised of Series. For xarray, Datasets are logically comprised of DataArrays. For GraphBLAS, Matrices are logically comprised of Vectors. Numpy is perhaps the odd one here in that it has one main data structure for everything.

I think it's nice to revisit some decisions like this more publicly even if we don't change anything.

**Comment by eriknw** [comment]
We discussed this in one of our weekly community calls, and (as I recall) we decided to keep the current behavior of default size of 0.
