### ISSUE TITLE
How to control parallelism?

### ISSUE THREAD

**Issue by alugowski** [python-graphblas/python-graphblas#532]
How to control how many threads a GraphBLAS operation may use?

What I've tried:

Since SuiteSparse:GraphBLAS uses OpenMP, `threadpoolctl` should be able to control it:
```python
with threadpoolctl.threadpool_limits(limits=2):
    res = mat @ mat
```

But there is no effect.

I also tried setting the option directly, but this does not seem to have an effect either:
```python
from suitesparse_graphblas import lib
lib.GxB_Global_Option_set_INT32(lib.GxB_GLOBAL_NTHREADS, 2)
```

**Comment by eriknw** [comment]
Great question! Let me count the ways:

1. Single operation: `A(nthreads=2) << A @ A`; `A(nthreads=2)[rows, cols] = B`
2. Single operation with `.new`: `gb.op.plus_times(A @ A).new(nthreads=2)`
3. Globally via config: `gb.ss.config["nthreads"] = 2`
4. Globally via SuiteSparse global context: `gb.ss.global_context["nthreads"] = 2`
5. Thread-local context via SuiteSparse contexts: `context = gb.ss.Context(nthreads=2)`

Methods with `**opts` (should be virtually everything) allow SuiteSparse-specific options to be passed in. Valid options are:
https://github.com/python-graphblas/python-graphblas/blob/a9598c56d109d973d2615d9695e1920b21266a98/graphblas/core/ss/descriptor.py#L136-L155

This ought to be better documented.

> I also tried setting the option directly, but this does not seem to have an effect either:
> 
> ```python
> from suitesparse_graphblas import lib
> lib.GxB_Global_Option_set_INT32(lib.GxB_GLOBAL_NTHREADS, 2)
> ```

I believe this used to work, but I think SuiteSparse:GraphBLAS 8 removed nthreads from global config and descriptor option, and instead moved nthreads to context. We updated our methods to work with this change but also kept the old behavior, hence why there are so many ways of doing it.

**Comment by alugowski** [comment]
Awesome! thanks!
